spring.application.name=RAG-APP
server.port=${PORT:8080}

openai.base.url=https://openrouter.ai/api/v1
openai.api.key=

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.owner=Mr.Prateek Gupta
info.app.version=4.0
info.app.swagger=http://localhost:8080/api/swagger-ui/index.html
info.app.api.docs=http://localhost:8080/api/v3/api-docs

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

rag.search.max-results=
rag.search.dynamic-threshold-multiplier=




